apiVersion: v1
kind: Secret
metadata:
  name: web-env
type: Opaque
stringData:
  DATABASE_NAME: "${DATABASE_NAME}"
  POSTGRES_DB: "${DATABASE_NAME}"
  DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
  POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
  DATABASE_USER: "${DATABASE_USER}"
  POSTGRES_USER: "${DATABASE_USER}"
  DJANGO_ALLOWED_HOSTS: "${DJANGO_ALLOWED_HOSTS}"
  DJANGO_CSRF_TRUSTED_ORIGINS: "${DJANGO_CSRF_TRUSTED_ORIGINS}"
  DJANGO_SECRET_KEY: "${DJANGO_SECRET_KEY}"
