services:
  db:
    image: postgres:bookworm
    container_name: brunneus-ferrum-malleus-db
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: brunneus-ferrum-malleus-web
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DJANGO_CSRF_TRUSTED_ORIGINS=${DJANGO_CSRF_TRUSTED_ORIGINS}
      - DATABASE_ENGINE=${DATABASE_ENGINE}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      # - DATABASE_HOST=localhost
      - DATABASE_HOST=brunneus-ferrum-malleus-db
      - DATABASE_PORT=${DATABASE_PORT}
      - TEST=${TEST}
    depends_on:
      - db

  caddy:
    image: caddy:alpine
    container_name: brunneus-ferrum-malleus-caddy
    ports:
      - 80:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./static:/srv/static
    depends_on:
      - web

volumes:
  pg_data:
